name: yocto_rpi3
on:
  workflow_dispatch:
  push:
    branches:
      - feature/*

jobs:
  checkout:
    runs-on: self-hosted

    steps:
    - name: checkout
      uses: actions/checkout@v2

  build_docker:
    runs-on: self-hosted
    needs: checkout
  
    steps:
    - name: Build docker
      working-directory: dockerfile
      run: |
        docker build \
        -t kallmanjaa . 
   
  build_yocto_image:
    runs-on: self-hosted
    needs: checkout
  
    steps:
    - name: run docker
      run: |
        echo "${GITHUB_WORKSPACE}"

