name: Building yocto_rpi3
on:
  workflow_dispatch:
    push:
      branches:
        - feature/*

jobs:
  checkout:
    runs-on: self-hosted

    steps:
    - name: checkout
      uses: actions/checkout@v2

  build:
    runs-on: self-hosted
    needs: checkout
  
    steps:
    - name: Build docker
      working-directory: docker
      run: |
        docker build \
        -t kallmanjaa . 
      
