name: yocto_rpi3
on:
  workflow_dispatch:
    push:
      branches:
        - feature/*

jobs:
  checkout:
    runs-on: self-hosted

    steps:
    - name: checkout
      uses: actions/checkout@v2
      
